# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  deploy:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "15:f3:c9:c6:37:9b:88:00:f3:f3:a3:b0:23:78:b9:67"
      - attach_workspace:
          at: ~/repo
      - store_artifacts:
          path: bin
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: |
            npm version from-git
            npm run release

workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy:
          context: NPM
